const cajasVarias = [
    {
        name: 'Caja A',
        efectivo: [
            {
                fecha: '01/04/24',
                codImp: 987654,
                numOp: '#ABCD1234',
                nomCliente: 'Juan Pérez',
                idCliente: 'CL-98765',
                valor: 12000,
            },
            {
                fecha: '05/04/24',
                codImp: 987654,
                numOp: '#EFGH5678',
                nomCliente: 'María García',
                idCliente: 'CL-98766',
                valor: 8000,
            },
        ],
        dolares: [
            {
                fecha: '02/04/24',
                codImp: 987654,
                numOp: '#WXYZ9876',
                nomCliente: 'John Doe',
                idCliente: 'CL-98767',
                valor: 15000,
            },
            {
                fecha: '06/04/24',
                codImp: 987654,
                numOp: '#IJKL4321',
                nomCliente: 'Jane Smith',
                idCliente: 'CL-98768',
                valor: 10000,
            },
        ],
        banco: [
            {
                fecha: '03/04/24',
                codImp: 987654,
                numOp: '#1234QRST',
                nomCliente: 'Robert Johnson',
                idCliente: 'CL-98769',
                valor: 20000,
            },
            {
                fecha: '07/04/24',
                codImp: 987654,
                numOp: '#5678UVWX',
                nomCliente: 'Sarah Williams',
                idCliente: 'CL-98770',
                valor: 18000,
            },
        ],
    },
    {
        name: 'Caja B',
        efectivo: [
            {
                fecha: '02/04/24',
                codImp: 987654,
                numOp: '#1234ABCD',
                nomCliente: 'Pedro López',
                idCliente: 'CL-98771',
                valor: 11000,
            },
            {
                fecha: '06/04/24',
                codImp: 987654,
                numOp: '#5678EFGH',
                nomCliente: 'Ana Martínez',
                idCliente: 'CL-98772',
                valor: 7500,
            },
        ],
        dolares: [
            {
                fecha: '03/04/24',
                codImp: 987654,
                numOp: '#WXYZ1234',
                nomCliente: 'Michael Johnson',
                idCliente: 'CL-98773',
                valor: 14000,
            },
            {
                fecha: '07/04/24',
                codImp: 987654,
                numOp: '#IJKL5678',
                nomCliente: 'Jessica Davis',
                idCliente: 'CL-98774',
                valor: 9500,
            },
        ],
        banco: [
            {
                fecha: '04/04/24',
                codImp: 987654,
                numOp: '#1234QRST',
                nomCliente: 'Christopher Miller',
                idCliente: 'CL-98775',
                valor: 19000,
            },
            {
                fecha: '08/04/24',
                codImp: 987654,
                numOp: '#5678UVWX',
                nomCliente: 'Emily Wilson',
                idCliente: 'CL-98776',
                valor: 17000,
            },
        ],
    },
    {
        name: 'Caja C',
        efectivo: [
            {
                fecha: '03/04/24',
                codImp: 987654,
                numOp: '#AABBCCDD',
                nomCliente: 'Carlos Hernández',
                idCliente: 'CL-98777',
                valor: 13500,
            },
            {
                fecha: '07/04/24',
                codImp: 987654,
                numOp: '#EEFFGGHH',
                nomCliente: 'Laura Pérez',
                idCliente: 'CL-98778',
                valor: 9200,
            },
        ],
        dolares: [
            {
                fecha: '04/04/24',
                codImp: 987654,
                numOp: '#IJKLMNOP',
                nomCliente: 'David Martinez',
                idCliente: 'CL-98779',
                valor: 16000,
            },
            {
                fecha: '08/04/24',
                codImp: 987654,
                numOp: '#QRSTUVWXYZ',
                nomCliente: 'Elena López',
                idCliente: 'CL-98780',
                valor: 10500,
            },
        ],
        banco: [
            {
                fecha: '05/04/24',
                codImp: 987654,
                numOp: '#1234ABCD',
                nomCliente: 'Gabriel Pérez',
                idCliente: 'CL-98781',
                valor: 22000,
            },
            {
                fecha: '09/04/24',
                codImp: 987654,
                numOp: '#5678EFGH',
                nomCliente: 'Olivia Rodriguez',
                idCliente: 'CL-98782',
                valor: 20000,
            },
        ],
    },
    {
        name: 'Caja D',
        efectivo: [
            {
                fecha: '04/04/24',
                codImp: 987654,
                numOp: '#QQWWEEFF',
                nomCliente: 'Mario García',
                idCliente: 'CL-98783',
                valor: 10000,
            },
            {
                fecha: '08/04/24',
                codImp: 987654,
                numOp: '#ZZXXCCVV',
                nomCliente: 'Natalia Martínez',
                idCliente: 'CL-98784',
                valor: 6700,
            },
        ],
        dolares: [
            {
                fecha: '05/04/24',
                codImp: 987654,
                numOp: '#AASSDDFF',
                nomCliente: 'Carlos Rodríguez',
                idCliente: 'CL-98785',
                valor: 12000,
            },
            {
                fecha: '09/04/24',
                codImp: 987654,
                numOp: '#GGHHJJLL',
                nomCliente: 'Sofía Pérez',
                idCliente: 'CL-98786',
                valor: 8000,
            },
        ],
        banco: [
            {
                fecha: '06/04/24',
                codImp: 987654,
                numOp: '#QQWWEEFF',
                nomCliente: 'Lucas García',
                idCliente: 'CL-98787',
                valor: 17000,
            },
            {
                fecha: '10/04/24',
                codImp: 987654,
                numOp: '#ZZXXCCVV',
                nomCliente: 'Valeria Martínez',
                idCliente: 'CL-98788',
            },
        ],
    },
    {
        name: 'Caja E',
        efectivo: [
            {
                fecha: '05/04/24',
                codImp: 987654,
                numOp: '#XXYYZZWW',
                nomCliente: 'Héctor Rodríguez',
                idCliente: 'CL-98789',
                valor: 13000,
            },
            {
                fecha: '09/04/24',
                codImp: 987654,
                numOp: '#AAAABBBB',
                nomCliente: 'Ana García',
                idCliente: 'CL-98790',
                valor: 8500,
            },
        ],
        dolares: [
            {
                fecha: '06/04/24',
                codImp: 987654,
                numOp: '#CCDDZZXX',
                nomCliente: 'Luis Martínez',
                idCliente: 'CL-98791',
                valor: 11000,
            },
            {
                fecha: '10/04/24',
                codImp: 987654,
                numOp: '#EEFFGGHH',
                nomCliente: 'María Pérez',
                idCliente: 'CL-98792',
                valor: 7000,
            },
        ],
        banco: [
            {
                fecha: '07/04/24',
                codImp: 987654,
                numOp: '#XXYYZZWW',
                nomCliente: 'Pedro Rodríguez',
                idCliente: 'CL-98793',
                valor: 18000,
            },
            {
                fecha: '11/04/24',
                codImp: 987654,
                numOp: '#AAAABBBB',
                nomCliente: 'Laura García',
                idCliente: 'CL-98794',
                valor: 16000,
            },
        ],
    },
];


  export default cajasVarias;